### ISSUE TITLE
How to connect to self hosted (Docker) Supabase?

### ISSUE THREAD

**Issue by PraveenGandhi** [tschuehly/htmx-supabase-spring-boot-starter#8]
Hi @tschuehly ,

Thank you for this starter. Could you please share some thoughts on the way to connect to [self hosted (Docker)](https://supabase.com/docs/guides/self-hosting/docker) Supabase?

Thank you.

**Comment by tschuehly** [comment]
Hello @PraveenGandhi,

you can connect to a local supabase instance that is started with the supabase cli with the following config:

```
supabase:
  projectId: default
  url: http://localhost:54321
  database:
    port: 54322
    host: 127.0.0.1
    username: postgres
    password: postgres
```

If you self host you should just be able to connect with the same configuration but adjusted ports and url.
